### ISSUE TITLE
Какие ошибки здесь вы обрабатываете? Обоснуйте необходимость try/catch

### ISSUE THREAD

**Issue by frontgirl** [titangro/jsGame#13]
https://github.com/titangro/jsGame/blob/15e2ed6d108225812bd5ce53065ee76ea303bc79/game.js#L249

**Comment by titangro** [comment]
Пытался избежать ошибки при тестировании вида:  ReferenceError: runGame is not defined. В игровом режиме ошибок нет. Убрал обработчик ошибок.
