### ISSUE TITLE
Что проверяется условием typeof item !== 'function' ? а что нужно проверять в данном методе?

### ISSUE THREAD

**Issue by frontgirl** [titangro/jsGame#17]
https://github.com/titangro/jsGame/blob/b18b18c06cb2fdecb5b62e273bf83c6be5a24286/game.js#L182

**Comment by titangro** [comment]
В тестах есть условие: 'Игнорирует символы, для которых в словаре передана не функция', для этого добавил условие в метод

**Comment by titangro** [comment]
Просмотрел еще раз, теперь понял: у меня метод actorFromSymbol() выдавал не всегда конструктор. Теперь поправил
