### ISSUE TITLE
Почему максимум ищется из одного элемента? Данный метод подразумевает сравнение 2х элементов. А в вашем случае в result всегда будет сохраняться очередной элемент, то есть код не имеет смысла.

### ISSUE THREAD

**Issue by frontgirl** [titangro/jsGame#6]
https://github.com/titangro/jsGame/blob/15e2ed6d108225812bd5ce53065ee76ea303bc79/game.js#L120

**Comment by titangro** [comment]
Поправил с использованием метода reduce()

**Comment by titangro** [comment]
Обновил метод, теперь возвращается сравнение из двух элементов
