### ISSUE TITLE
Какова цель try/catch здесь? Какие ошибки вы обрабатываете?

### ISSUE THREAD

**Issue by frontgirl** [titangro/jsGame#8]
https://github.com/titangro/jsGame/blob/15e2ed6d108225812bd5ce53065ee76ea303bc79/game.js#L232

**Comment by titangro** [comment]
Поправил ошибку с помощью toString(), т.к. при обработке объекта, выводилась ошибка

**Comment by frontgirl** [comment]
Какая именно ошибка? Что делает метод toString()? какого типа ваш item? (кстати, тоже не самое лучшее название - это же строка уровня? Давайте назовем соответственно). Мне кажется, вы преобразуете строку в строку.

**Comment by titangro** [comment]
Похоже, что так. В каком то случае у меня появлялся объект за место строки. При этом только на тестах, в процессе игры ошибки не было. Ошибка вида: ReferenceError: runGame is not defined.
Изменил название item на string, убрал приведение к строке.
